version: '3.8'
services:
  gembot:
    container_name: gembot
    image: node:lts-alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose: [ 8000 ]
    env_file: [ docker.env ]
    mem_limit: 100M
    command: /bin/sh -c "npm run dev"
    restart: always
